### ISSUE TITLE
Formatting and linting requires `CocRestart` + saving twice to start working

### ISSUE THREAD

**Issue by tony** [fannheyward/coc-biome#13]
May be related to #11, but in biome 1.4.0 and vim 9.0.

# Workaround (For each vim instance)

_Works with #12_

1. Launch vim
2. Open file, e.g. `App.tsx`
3. Run `:CocRestart`
4. Save once `:w` (no formatting yet)
5. Save a second time `:w`
6. Formats correctly

**Comment by fannheyward** [comment]
Try v1.4.1

**Comment by fannheyward** [comment]
Can't reproduce, linting and formatting works on saving with `w`.

Does `:CocCommand editor.action.formatDocument` work?

**Comment by fannheyward** [comment]
Add `"biome.trace.server": "verbose"` to coc-settings.json, after `w`, check `:CocCommand workspace.showOutput Biome` for the formatting request and response.

**Comment by fannheyward** [comment]
Still can't reproduce, after `w`, the `textDocument/formatting` request is sent and responded.

Tested with your `cv` project.

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-biome/assets/345274/692d8aee-8950-4dc1-835c-b6f4d84e1cda

You can set `"biome.trace.server": "messages"` to simple the trace logs.

**Comment by fannheyward** [comment]
> Launched vim via packages/react

Reproduced. It should be a problem caused by the workspace root detecting. When you're in `packages/react` folder, coc use this as project root, but there wasn't `biome.json` file, coc-biome didn't work.

Set `"biome.requireConfiguration": false` and try again, this won't require must-have `biome.json` to work

**Comment by fannheyward** [comment]
The key issue is workspace root detecting.

> biome.json in the root of the repo isn't used

coc uses `packages/react` as project root, coc-biome only search `biome.json` in the root folder.

Why coc uses this as project root? After you open `src/App.tsx`, coc tried to find project root with root patterns, here's `package.json`, found and use it.

coc-biome can't search upwards to use biome.json in parent folders.

Why `CocRestart` works for your expected? Have no idea, I can't reproduce this, `CocRestart` and `:w` in `packages/react` won't use the biome.json in parent root.
